### ISSUE TITLE
gulp_caller still used?

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen-analysis-defects#108]
[Says here](https://github.com/materialsproject/pymatgen/blob/40cbf1d7c47bb2eb75509780e356c9877ae9c2f7/docs_rst/installation.rst#optional-non-python-programs) the pymatgen `gulp_caller` module is "used extensively" by `pymatgen-analysis-defects`. I assume that's outdated? Can't find any mention of gulp here. Thinking of removing the gulp module from pymatgen.

**Comment by jmmshn** [comment]
@janosh, nope gulp is not used in any of the code.

**Comment by janosh** [comment]
Thanks for confirming. Shyue decided to keep `gulp` for now anyway in https://github.com/materialsproject/pymatgen/pull/2861.
