### ISSUE TITLE
Dependency version conflicts

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen-analysis-defects#124]
I'm getting dependency version conflicts when trying to update to  pymatgen-analysis-defects 2023.5.4 with atomate2.

```
The conflict is caused by:
    atomate2[strict] 0.0.10.post256+ga84e4d33.d20230508 depends on pymatgen>=2023.1.9
    atomate2[strict] 0.0.10.post256+ga84e4d33.d20230508 depends on pymatgen==2023.3.23; extra == "strict"
    emmet-core 0.54.2 depends on pymatgen>=2021.3
    lobsterpy 0.2.9 depends on pymatgen>=2023.1.20
    mp-api 0.33.1 depends on pymatgen>=2022.3.7
    pymatgen-analysis-defects 2023.5.4 depends on pymatgen==2023.1.9
```

It seems like pymatgen-analysis-defects 2023.5.4 is pinned to pymatgen==2023.1.9 rather than a more flexible ">=".

Is there any chance you can push a new version with more relaxed dependencies.

**Comment by jmmshn** [comment]
Sorry this was down to avoid a bug in pymatgen that was introduced after this but fixed on master now. I'll depeg it and live with the failing tests for now.  Should be fixed with the next pymatgen release.

**Comment by jmmshn** [comment]
@utf new version release after pymatgen update.
