### ISSUE TITLE
FormationEnergyDiagram() in thermo module breaks for single-element systems

### ISSUE THREAD

**Issue by kinziefarnell** [materialsproject/pymatgen-analysis-defects#125]
I have been working on a calculation of vacancy formation energy for cubic Si, and am having problems with calling FormationEnergyDiagram() from thermo.py because my system has only one element. The issue is concerning the pd_entries argument to FormationEnergyDiagram()
To get the pd_entries, I run:
`pd_entries = mpr.get_entries_in_chemsys("Si")`
After passing this into FormationEnergyDiagram() , I get the following error:
```
ValueError                                Traceback (most recent call last)
Cell In[18], line 1
----> 1 fed = FormationEnergyDiagram(defect_entries, pd_entries, vbm, bulk_entry = bulk_entry)

File <string>:9, in __init__(self, defect_entries, pd_entries, vbm, band_gap, bulk_entry, inc_inf_values)

File ~/miniconda3/envs/atomate2-defects/lib/python3.10/site-packages/pymatgen/analysis/defects/thermo.py:245, in FormationEnergyDiagram.__post_init__(self)
    242     entries.append(ComputedEntry.from_dict(d_))
    243     entries.append(ComputedEntry.from_dict(d_))
--> 245 self.chempot_diagram = ChemicalPotentialDiagram(entries)
    246 chempot_limits = self.chempot_diagram.domains[
    247     bulk_entry.composition.reduced_formula
    248 ]
    250 if self.inc_inf_values:

File ~/miniconda3/envs/atomate2-defects/lib/python3.10/site-packages/pymatgen/analysis/chempot_diagram.py:102, in ChemicalPotentialDiagram.__init__(self, entries, limits, default_min_limit)
     96 (
     97     self._hyperplanes,
     98     self._hyperplane_entries,
     99 ) = self._get_hyperplanes_and_entries()
    101 if self.dim < 2:
--> 102     raise ValueError("ChemicalPotentialDiagram currently requires phase diagrams with 2 or more elements!")
    104 if len(self.el_refs) != self.dim:
    105     missing = set(self.elements) - set(self.el_refs)
ValueError: ChemicalPotentialDiagram currently requires phase diagrams with 2 or more elements!
```
The call is failing because FormationEnergyDiagram() calls ChemicalPotentialDiagram(), which requires 2 or more elements to make a phase diagram, and I only have one element. I'm not sure how to address the issue, do you have any suggestions?

**Comment by jmmshn** [comment]
So `ChemicalPotentialDiagram` does not handle single-element phase diagrams.  @mattmcdermott I'm not sure how easy of a fix that would be to get it in there.

In the meantime, adding a dummy element like O to the phase diagram seems to solve this problem.

The code below demonstrates how this might be done.

```python
from pymatgen.analysis.defects.thermo import FormationEnergyDiagram, DefectEntry, ComputedEntry, plot_formation_energy_diagrams
from pymatgen.analysis.defects.generators import VacancyGenerator
from pymatgen.ext.matproj import MPRester
mpr = MPRester()    
struct = mpr.get_structure_by_material_id("mp-149")
gen = VacancyGenerator()
defect = next(gen.generate(struct))
dent = DefectEntry(defect, 0, sc_entry=ComputedEntry("Si", 100), corrections={"freysoldt" : 0})
fed = FormationEnergyDiagram([dent], pd_entries=[ComputedEntry("Si", 0), ComputedEntry("O", 0)], vbm=0, band_gap=10, bulk_entry=ComputedEntry("Si", 0))
plot_formation_energy_diagrams(fed, rich_element="Si")
```

**Comment by mattmcdermott** [comment]
Yes, adding a dummy element is a good temporary fix! 

I can update `ChemicalPotentialDiagram` to allow single-element systems, but it would only be for convenience in downstream use. There isn't any new information offered as it would just return the `energy_per_atom` of the ground-state entry. 

It might make more sense to add something to `FormationEnergyDiagram` to catch single-element systems. If you think the former is cleaner instead, though, I am happy to tackle it

**Comment by jmmshn** [comment]
@mattmcdermott Thanks for the info!  So I was looking to spoof it within `FormationEnergyDiagram` but it bascially involved spoofing the `ChemicalPotentialDiagram` behavior since I do call various methods from that classe.  So I figured you would be able to spoof it better since you are more familiar.

**Comment by jmmshn** [comment]
So the main functions that actually get the data for the diagrams does allow for this:
 
https://github.com/materialsproject/pymatgen-analysis-defects/blob/e6ed8d6745bb77fc860a9e9dba239464bfe3512f/pymatgen/analysis/defects/thermo.py#L526

So the standard workflow should be 1. get the chempost using a "rich element limit"
https://github.com/materialsproject/pymatgen-analysis-defects/blob/e6ed8d6745bb77fc860a9e9dba239464bfe3512f/pymatgen/analysis/defects/thermo.py#L597

Then feed that dictionary into the `get_transitions` function.

**Comment by jmmshn** [comment]
Since this is resolved I will close this
