### ISSUE TITLE
Can we remove the numpy pin

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen-analysis-defects#130]
Currently, the numpy version is set to `numpy<=1.23.5`. @jmmshn, this is causing some dependency issues for me. Any chance we can remove the pin?

**Comment by jmmshn** [comment]
ok looks like the problem was solved recently:
https://github.com/SINGROUP/dscribe/issues/106
I think removing it will be OK.

**Comment by jmmshn** [comment]
So I noticed some other deps problems specifically related to describe.
I have a PR with this too I'll merge ours

**Comment by arosen93** [comment]
Okay 😅 I am closing my PR because this is annoying.
