### ISSUE TITLE
Missing file (get_corr.sh)?

### ISSUE THREAD

**Issue by ab5424** [materialsproject/pymatgen-analysis-defects#157]
Hi,

the jupyter notebook in [`docs/source/content/freysoldt-correction.ipynb`](https://github.com/materialsproject/pymatgen-analysis-defects/blob/main/docs/source/content/freysoldt-correction.ipynb) says that there should be a `get_corr.sh` script in the `/tests/test_files/v_N_GaN` directory. However, I can't find it in that folder or anywhere else in the repo.

**Comment by jmmshn** [comment]
hi @ab5424  thanks for flagging this I will add the script

**Comment by jmmshn** [comment]
I updated the docs, you can just run the `sxdefectalign` call from the top of the `corr.out` and `corr_align.out` files to get the data you need to compare.  I think I had a script in there but it was doing lots of copying that was making the directory messy so this was cleaner.

**Comment by jmmshn** [comment]
addressed in #160
