### ISSUE TITLE
[Bug]: Incorrect formation energies in FormationEnergyDiagram

### ISSUE THREAD

**Issue by kayahans** [materialsproject/pymatgen-analysis-defects#164]
### Problem

Formation energy term in the line below is wrong, please see the link for the file and location

> (self.dft_energies[Element(el)] + chempots[Element(el)]) * fac

https://github.com/materialsproject/pymatgen-analysis-defects/blob/564210e6fbd98793928da722e6154bc010aad1c1/pymatgen/analysis/defects/thermo.py#L459C17-L459C73

### Proposed Solution

the value of " chempots[Element(el)]" variable above already includes DFT energy meaning the chempot is $\mu^0 + \Delta\mu$ as defined in pymatgen. Adding "self.dft_energies[Element(el)] " makes the line above equal to $2\mu^0 + \Delta\mu$

**Comment by jmmshn** [comment]
I think this line explains it:

https://github.com/materialsproject/pymatgen-analysis-defects/blob/564210e6fbd98793928da722e6154bc010aad1c1/pymatgen/analysis/defects/thermo.py#L290-L293

I think this was originally the DFT energy but then I realized we needed the flexibility to replace the actual atomic reference energy but the `dft_energies` name was not changed. 
I'm open to changing it to another name if you have any sugestions please submit a PR.


https://github.com/materialsproject/pymatgen-analysis-defects/blob/564210e6fbd98793928da722e6154bc010aad1c1/pymatgen/analysis/defects/thermo.py#L290-L293

**Comment by jmmshn** [comment]
If the question is resolved I will close this.
