### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by msehabibur** [materialsproject/pymatgen-analysis-defects#170]
### Problem

I wanted to create an interstitial defect using this script, but it does not work. It shows class is not iterable. 

from pymatgen.analysis.defects.generators import DefectGenerator, InterstitialGenerator
initial_struct = Structure.from_file('POSCAR')
inter_element = Element('C')
defects = [defect for defect in InterstitialGenerator(initial_struct, inter_element)]

### Proposed Solution

Explain, what are the inputs to the function and class.

**Comment by jmmshn** [comment]
I added some documentation for this: both the README and in the tutorials:

https://materialsproject.github.io/pymatgen-analysis-defects/content/defining-defects.html#

Hope this helps!

**Comment by msehabibur** [comment]
Thank you so much! Can you please tell me how I can get a POSCAR file from each defect object?

from mp_api.client import MPRester
from pymatgen.io.vasp import Chgcar
from pymatgen.analysis.defects.generators import generate_all_native_defects
from pymatgen.io.vasp.inputs import Poscar


API_KEY = ""
with MPRester(API_KEY) as mpr:
    chgcar = mpr.get_charge_density_from_material_id("mp-804")


for defect in generate_all_native_defects(chgcar):
    print(defect)

**Comment by jmmshn** [comment]
So the `get_supercell_structure()` fuction for each `Defect` object should take care of that.

There is already some documentation on it here:
https://materialsproject.github.io/pymatgen-analysis-defects/content/defining-defects.html#obtaining-the-simulation-supercell

**Comment by jmmshn** [comment]
If the question is resolved I will close this issue.
