### ISSUE TITLE
how to find 'tetrahedral' and 'octahedral' Interstitial site 

### ISSUE THREAD

**Issue by AlexHeustc** [materialsproject/pymatgen-analysis-defects#27]
when I used pymatgen=2022.5.26 , I import class 'StructureMotifInterstitial' to find  'tetrahedral' and 'octahedral' Interstitial site in a structure. In pymatgen-analysis-defects,I can't find such a module.

**Comment by jmmshn** [comment]
Hi @AlexHeustc, The `StructureMotifInterstitial` class is no longer supported in the new code.  In my testing, the `CharngeInsertionAnalyzer` works well enough for most applications that you should just use that. 
The internal documentation should be enough to show you how to use it, but I will make a tutorial for these things soon.

If you absolutely have to use `StructureMotifInterstitial` you can pip install the older version of the code.
