### ISSUE TITLE
Vacancy naming convention

### ISSUE THREAD

**Issue by kavanase** [materialsproject/pymatgen-analysis-defects#29]
Hi! 
@utf and I were discussing the naming convention for defects (and defect calculation folders), and were thinking that `Va` in `Va_X` for vacancies looks like an element symbol.
Using something different, like `v_X` may be slightly more intuitive and easier to pick distinguish when e.g. looking at a list of defects / defect folders (where `X_i`, `X_Y` and `v_X` are easier to pick out, as interstitials, substitutions and vacancies).

An added point would be that `v_X` would correspond to the conventional Kroger-Vink notation, as the names for interstitials and substitutions already do here:
https://en.wikipedia.org/wiki/Kr%C3%B6ger%E2%80%93Vink_notation

**Comment by jmmshn** [comment]
Yeah that makes sense!
I'll fix it in the next release.

> @utf and I were discussing the naming convention for defects (and defect calculation folders),
I don't think folder names are used in any real sense in the code so the only thing that needs changing is here:
https://github.com/materialsproject/pymatgen-analysis-defects/blob/215e1bc1a590731ef67f22916d71636cc2e835c7/pymatgen/analysis/defects/core.py#L214
