### ISSUE TITLE
Freysold correction

### ISSUE THREAD

**Issue by misaraty** [materialsproject/pymatgen-analysis-defects#40]
I was pleasantly surprised to find an excellent tutorial on the calculation of defect formation energy, but there is no code for the correction term found on this page https://materialsproject.github.io/pymatgen-analysis-defects/tutorials/1-quickstart.html. How to take into account the Freysold correction?

Thanks!

**Comment by jmmshn** [comment]
Content from email that was not updated here:
>The Freysoldt correction is handled in the background automatically.
>There is some capability to interact with it but that part of the code is not super flexible yet.
