### ISSUE TITLE
Kumagai/eFNV Correction?

### ISSUE THREAD

**Issue by kavanase** [materialsproject/pymatgen-analysis-defects#47]
Hi @jmmshn!
I noticed there is no Kumagai / eFNV correction function in `corrections.py`, as there was in the previous `pymatgen` module (I actually went looking for this because I had a fix for a small bug to push). I was just wondering if this will be added to this package?
It was useful for calculating the defect charge corrections in anisotropic systems!
Cheers!

**Comment by jmmshn** [comment]
Hi @kavanase, I do plan on adding Kugami and eFNV into the code.  I was just trying to get a minimal working version of the code up to allow progress for the atomate2 workflows.
I will get to those soon.  Can you send me a link to the bug you fixed?

**Comment by kavanase** [comment]
Ok cool, sounds good!
For the bug, it was in the old `pymatgen` corrections code. Basically it was to change
```python
entry.parameters["kumagai_meta"] = (dict(self.metadata))
```
to 
```python
entry.parameters["kumagai_meta"].update(dict(self.metadata))
```
in `KumagaiCorrection.get_correction()`, `pymatgen/analysis/defects/corrections.py` to prevent the other relevant `kumagai_meta` (`kumagai_electrostatic` etc.) being overwritten when run `KumagaiCorrection.get_correction(defect_entry)` was run (to get the charge correction plot and energy). This function is also called in `finite_size_charge_correction.get_correction_kumagai(defect_entry...)`.
I was gonna PR this to `pymatgen` but the code has been removed in the recent refactoring of the defects code

**Comment by jmmshn** [comment]
> I was gonna PR this to pymatgen but the code has been removed in the recent refactoring of the defects code
I really wanted to keep the old code and just have this mask the old code upon installation but was vetoed in the decision-making process.

Do you have any experience with eFNV correction and implementation?  We never actually used it in the Van de Walle group.

**Comment by jmmshn** [comment]
So I'm working on porting Kumagai correction over.
The only place I see the eFNV correction is in pydefect which looks like they use a site-based trick before they calculate anything.  Let me know if there is another place where eFNV is implements that fits our purposes.
@nwinner is looking into using the actual freysoldt correction script to handle this that is also an option.

**Comment by nwinner** [comment]
eFNV should be the same as Kumagai right? Or am I mixing up my terminology

**Comment by jmmshn** [comment]
Ok I thought eFNV was the new 2D one from Freysoldt but I guess that would just be FN

**Comment by kavanase** [comment]
Hi @jmmshn, sorry for being slow to get back to you! (I was in transit this week, funnily enough from Kumagai's group in Japan back to London)
Yes I've experience with using both the Freysoldt (FNV) and Kumagai (eFNV) corrections in my work and others' I've supervised, through the `pymatgen` implementations. Kumagai has his method (eFNV) implemented in his `pydefect` code as well as the version in the older `pymatgen` code (just called `KumagaiCorrection`), but I thought the implementations were similar, if not the same, between these (using the site potentials to generate the correction plot).
The idea is very similar to the original Freysoldt (FNV) scheme, but that's typically done by using the planar-average electrostatic potential (via the `LOCPOT`) – which doesn't work so well for anisotropic-dielectric/non-cubic systems, so one of the reasons why this is different to the Kumagai one.

And yeah I'm not sure what the acronym is for the new 2D Freysoldt one!

**Comment by jmmshn** [comment]
OK, I just checked and it does look like `pydefect` and the old `pymatgen` code are using the same data.

https://github.com/kumagai-group/pydefect/blob/7a1a07e05aaadb9d3afdfab6dde77a8d057c36bb/pydefect/cli/vasp/make_calc_results.py#L7-L14

https://github.com/materialsproject/pymatgen/blob/baf62b77788fc43387e15b1e0b60094132815c47/pymatgen/analysis/defects/tests/test_corrections.py#L144-L150

I plan on porting over the `pydefect` code after thanksgiving on the US side and MRS so this will have to wait a bit.

**Comment by jmmshn** [comment]
Example of how to use it is here:
https://github.com/materialsproject/pymatgen-analysis-defects/blob/72ec88a5ab6a7d5d86d2152dbf4d57fa76fb7bfc/tests/test_corrections.py#L49

**Comment by yuan-gist** [comment]
So far I saw two bugs in `kumagai.py`:

First:

```
def _check_import_pydefect():
    """Import pydefect if it is installed."""
    if __has_pydefect__:
        raise ModuleNotFoundError(
            "vise/pydefect is not installed. Please install it first."
        )
```
The correct one should be "if not __has_pydefect__"

Second:
```
    **bulk**_potentials = [site.properties["potential"] for site in **defect**_structure]
    **defect**_potentials = [site.properties["potential"] for site in **bulk**_structure]
```

**Comment by jmmshn** [comment]
Yeah I added support for this at the request of anothger user and have not been using this at all.  As such this is not tested.  If you notice anything please PR.  Thanks!
