### ISSUE TITLE
VoronoiInterstitialGenerator

### ISSUE THREAD

**Issue by yayapa** [materialsproject/pymatgen-analysis-defects#55]
Hello! Thank you for your new Package!
I am trying to change to the newest pymatgen version and found out that the old line does not work anymore:
`from pymatgen.analysis.defects.generators import VoronoiInterstitialGenerator`
Unfortunately, I was not be able to find the good replacement in the existing package. Do you plan to add it in the future versions as it was earlier, for example in[ v2021.x.X](https://github.com/materialsproject/pymatgen/blob/v2021.2.8/pymatgen/analysis/defects/generators.py)?

**Comment by jmmshn** [comment]
Hi @yayapa,
In my experience, the VoronoiInterstitialGenerator did not work very well in terms of finding good initial guess for sites so I did not port it over to the new code.
Can you try the charge density based generator?

**Comment by jmmshn** [comment]
Also if you have a case that you think the `VoronoiInterstitialGenerator` works better please let me know.
I can dedicate some time to port that over as well.

**Comment by yayapa** [comment]
@jmmshn thank you for the answer. This was used for detecting candidates of interstitial impurities and the Voronoi tessellation was important for the physical logic in the special case. Therefore, it would be very helpful, if you add an implementation in the new defects module. Since the main feature was not the Voronoi (can be taken [DetailedVoronoiConttainer](https://pymatgen.org/pymatgen.analysis.chemenv.coordination_environments.voronoi.html?highlight=detailedvoronoicontainer#pymatgen.analysis.chemenv.coordination_environments.voronoi.DetailedVoronoiContainer), but the additional screening for sublattice equivalent with [PointDefectComparator](https://github.com/materialsproject/pymatgen/pull/2582) (that reduced the number of candidates and, unfortunately, also was removed in new versions), is there any alternatives for that?

**Comment by jmmshn** [comment]
@yayapa  so the easiest way it to just peg pymatgen to the version prior to the change `2022.7.8` should work.

**Comment by jmmshn** [comment]
Resolved in PR #82 

Example usage:
https://github.com/materialsproject/pymatgen-analysis-defects/blob/aff3f20d4697867672a0665caa3fa5d5364b5e29/tests/test_generators.py#L84-L91
