### ISSUE TITLE
no license file

### ISSUE THREAD

**Issue by njzjz** [materialsproject/pymatgen-analysis-defects#60]
Hi, I want to add this package to conda-forge, but I don't find any LICENSE file in the source code. Instead, I only found a license key in `pyproject.toml`.

https://github.com/materialsproject/pymatgen-analysis-defects/blob/5e12ae4e4acc62f28db18bb5bc54521142e8e886/pyproject.toml#L22

**Comment by jmmshn** [comment]
@njzjz thank you for raising this!
I think the add on namespace packages are suppose to inherited the same license as pymatgen.  I will add the MIT license next week though.

**Comment by jmmshn** [comment]
@njzjz  nvm looks like all the new stuff requires the LBL modified license, I have updated the repo thanks for reporting this.
