### ISSUE TITLE
Missing VoronoiInterstitialGenerator when installing from conda-forge

### ISSUE THREAD

**Issue by yliu1240** [materialsproject/pymatgen-analysis-defects#87]
Hi, all!
I'm trying to use the VoronoiInterstitialGenerator but find that this function is missing if I install the Pymatgen-analysis-defects from conda-forge channel. Is it because that the newest version is not updated yet? Or shall I install from pip?

Thanks in advance!

**Comment by jmmshn** [comment]
So I'm was not aware the package was even on conda-forge I have only released pip.
I have updated the release to 2023.01.08 which should have all the new stuff.

**Comment by jmmshn** [comment]
It looks like the conda-forge one is just automatically created from `pypi` somehow.  Either way, the updated code should be on both now.
